FROM public.ecr.aws/lambda/python:3.8

#RUN python3.9 -m pip install --upgrade pip && \
RUN pip install https://github.com/alexeygrigorev/tflite-aws-lambda/blob/main/tflite/tflite_runtime-2.7.0-cp38-cp38-linux_x86_64.whl?raw=true

RUN pip install Pillow requests

COPY lambda_function.py .
COPY dino_dragon_v1.tflite .

CMD ["lambda_function.lambda_handler"]